version: '3.9'

services:
  mongo_1:
    image: ehab215/docker_project:mongo-${MONGO_DB_VER}
    ports:
       - "27017:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
      - yolo_to_mongo_primary
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_2:
    image: ehab215/docker_project:mongo-${MONGO_DB_VER}
    ports:
      - "27018:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_3:
    image: ehab215/docker_project:mongo-${MONGO_DB_VER}
    ports:
      - "27019:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_init:
    image: ehab215/docker_project:mongo-${MONGO_DB_VER}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - mongoCluster
    build:
      context: ./mongo_init
      dockerfile: Dockerfile
    depends_on:
      - mongo_1
      - mongo_2
      - mongo_3

  polybot:
    image: ehab215/docker_project:polybot-${POLYBOT_IMG_NAME}
    ports:
      - "8443:8443"
    env_file:
      - .env
    networks:
      - mongoCluster
      - yolo_to_mongo_primary

  yolo5_app:
    image: ehab215/docker_project:yolo5-${YOLO5_IMG_NAME}
    ports:
      - "8081:8081"
    volumes:
      - $HOME/aws/credentials:$HOME/aws/credentials
    env_file:
      - .env
    networks:
      - yolo_to_mongo_primary
      - mongoCluster

networks:
  mongoCluster:
    external: false
  yolo_to_mongo_primary:
    external: false

volumes:
  mongo_data: