version: '3.8'

services:
  mongo_1:
    image: mongo:${MONGO_DB_VER}
    ports:
       - "27017:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
      - yolo_to_mongo_primary
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_2:
    image: mongo:${MONGO_DB_VER}
    ports:
      - "27018:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_3:
    image: mongo:${MONGO_DB_VER}
    ports:
      - "27019:27017"
    env_file:
      - .env
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongo_init:
    image: mongo:${MONGO_DB_VER}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - mongoCluster
    build:
      context: ./mongo_init
      dockerfile: Dockerfile
    depends_on:
      - mongo_1
      - mongo_2
      - mongo_3

  polybot:
    image: polybot:${POLYBOT_VER}
    ports:
      - "8443:8443"
    env_file:
      - .env
    networks:
      - mongoCluster
      - yolo_to_mongo_primary
    secrets:
      - token

  yolo5_app:
    image: yolo5:${YOLO5_IMG_NAME}
    ports:
      - "8081:8081"
    volumes:
      - $HOME/aws/credentials:$HOME/aws/credentials
    env_file:
      - .env
    networks:
      - yolo_to_mongo_primary
      - mongoCluster
    secrets:
      - token

networks:
  mongoCluster:
    external: true
  yolo_to_mongo_primary:
    external: true

secrets:
  token:
   external: true

volumes:
  mongo_data: